# Generated by Django 5.2.11 on 2026-02-27 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('specs', models.JSONField(help_text='Flexible dictionary of technical specifications.')),
                ('raw_summary', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(max_length=500)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash to prevent duplicate entries.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hardware Manual',
                'verbose_name_plural': 'Hardware Manuals',
                'ordering': ['-created_at'],
            },
        ),
    ]
